# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XMUI_OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!  
  
  # facebook 的性能优化方案，在子线程布局、渲染、解码等
  pod "Texture"
  
end
