# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 导入flutter页面需要的
flutter_application_path = '../flutter_m'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'XMUI_OC' do
  use_frameworks!
  # 导入flutter页面需要的
  install_all_flutter_pods(flutter_application_path)
  
end

# 新增的配置 - # 导入flutter页面需要的
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end

